#!/usr/bin/env python3

import sys

from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Date, ForeignKey
from sqlalchemy.orm import relationship
meta = MetaData()
engine = create_engine(f"sqlite:///concert_events.sqlite",echo=True)

comments = Table(
    'comments',meta,
    Column('id',Integer,primary_key=True),
    Column('username',String),
    Column('comment',String),
    Column('created',Date),
    Column('user_id',Integer,ForeignKey('users.id')),
    Column('concert_id',Integer,ForeignKey('concerts.id'))
    )

users = Table(
    'users',meta,
    Column('id',Integer,primary_key=True),
    Column('username',String),
    Column('email',String),
    Column('password_hash',String),
    Column('comments',ForeignKey('comments.id')))

concerts = Table(
	'concerts',meta,
	Column('id',Integer,primary_key=True),
    Column('event_creator',String),
	Column('event_name',String),
	Column('event_description',String),
	Column('event_date',Date),
	Column('event_genre',String),
	Column('event_venue',String),
	Column('ticket_count',Integer),
	Column('ticket_price',Integer),
    Column('event_status',String),
	Column('event_image',String),
    Column('comments',ForeignKey('comments.id')))

tickets = Table(
    'tickets',meta,
    Column('id',Integer,primary_key=True),
    Column('event_id',Integer),
    Column('ticket_owner',String),
    Column('ticket_quantity',Integer))
    

meta.create_all(engine)
